import { FormEvent, useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  ArrowUpRight,
  CheckCircle2,
  ChevronRight,
  ClipboardCheck,
  Clock3,
  FileText,
  HeartPulse,
  Loader2,
  LockKeyhole,
  RefreshCw,
  ShieldCheck,
  Sparkles,
  Stethoscope,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { analyzePatient, ClinicalAnalysisResponse, ClinicalApiError, PatientRequest } from "@/api/clinicalAnalysis";

const LOGO_URL = "/prism-signal-logo.png";

const initialForm: PatientRequest = {
  age: 58,
  bmi: 28.4,
  hba1c: 7.2,
  fasting_glucose: 142,
  egfr: 78,
  systolic_bp: 132,
  diastolic_bp: 82,
  current_meds: [],
};

const medicationOptions = ["Metformin", "SGLT2i", "GLP-1", "ACE inhibitor", "ARB", "Statin"];

function fieldError(label: string, value: number, min: number, max: number) {
  if (!Number.isFinite(value)) return `${label} is required.`;
  if (value < min || value > max) return `${label} must be between ${min} and ${max}.`;
  return "";
}

function formatLabel(value: string) {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function statusTone(value: string) {
  const normalized = value.toLowerCase();
  if (normalized.includes("emergency") || normalized.includes("urgent") || normalized.includes("high")) return "danger";
  if (normalized.includes("moderate") || normalized.includes("review") || normalized.includes("attention")) return "attention";
  return "stable";
}

function Metric({ label, value, unit }: { label: string; value: string | number; unit?: string }) {
  return (
    <div className="metric-block">
      <p className="eyebrow">{label}</p>
      <p className="metric-value">{value}<span>{unit}</span></p>
    </div>
  );
}

function StatusBadge({ value }: { value: string }) {
  return <span className={`status-badge ${statusTone(value)}`}>{formatLabel(value)}</span>;
}

function PatientForm({
  form,
  setForm,
  onSubmit,
  loading,
  error,
}: {
  form: PatientRequest;
  setForm: (value: PatientRequest) => void;
  onSubmit: (event: FormEvent<HTMLFormElement>) => void;
  loading: boolean;
  error: string;
}) {
  const errors = useMemo(() => ({
    age: fieldError("Age", form.age, 18, 90),
    bmi: fieldError("BMI", form.bmi, 15, 60),
    hba1c: fieldError("HbA1c", form.hba1c, 4, 15),
    fasting_glucose: fieldError("Fasting glucose", form.fasting_glucose, 50, 350),
    egfr: fieldError("eGFR", form.egfr, 15, 150),
    systolic_bp: fieldError("Systolic blood pressure", form.systolic_bp, 90, 220),
    diastolic_bp: fieldError("Diastolic blood pressure", form.diastolic_bp, 50, 130),
  }), [form]);
  const hasErrors = Object.values(errors).some(Boolean) || form.diastolic_bp >= form.systolic_bp;

  const updateNumber = (key: keyof PatientRequest, value: string) => {
    const numeric = value === "" ? Number.NaN : Number(value);
    setForm({ ...form, [key]: numeric });
  };

  const toggleMedication = (medication: string) => {
    const current = form.current_meds.includes(medication)
      ? form.current_meds.filter((item) => item !== medication)
      : [...form.current_meds, medication];
    setForm({ ...form, current_meds: current });
  };

  return (
    <form className="intake-form" onSubmit={onSubmit} noValidate>
      <div className="section-heading">
        <div>
          <p className="eyebrow teal">Patient intake</p>
          <h2>Trace the signal before the next decision.</h2>
        </div>
        <span className="provenance"><ShieldCheck size={13} /> Backend validated</span>
      </div>
      <p className="section-copy">Enter the measurements available for this assessment. The analysis is generated by the connected clinical intelligence service.</p>

      {error && (
        <div className="error-banner" role="alert">
          <AlertTriangle size={18} />
          <div><strong>Analysis unavailable</strong><p>{error}</p></div>
        </div>
      )}

      <div className="form-grid">
        <label className="field"><span>Age <small>years</small></span><input aria-label="Age" type="number" min="18" max="90" value={Number.isNaN(form.age) ? "" : form.age} onChange={(e) => updateNumber("age", e.target.value)} />{errors.age && <em>{errors.age}</em>}</label>
        <label className="field"><span>BMI <small>kg/m²</small></span><input aria-label="BMI" type="number" step="0.1" min="15" max="60" value={Number.isNaN(form.bmi) ? "" : form.bmi} onChange={(e) => updateNumber("bmi", e.target.value)} />{errors.bmi && <em>{errors.bmi}</em>}</label>
        <label className="field"><span>HbA1c <small>%</small></span><input aria-label="HbA1c" type="number" step="0.1" min="4" max="15" value={Number.isNaN(form.hba1c) ? "" : form.hba1c} onChange={(e) => updateNumber("hba1c", e.target.value)} />{errors.hba1c && <em>{errors.hba1c}</em>}</label>
        <label className="field"><span>Fasting glucose <small>mg/dL</small></span><input aria-label="Fasting glucose" type="number" step="0.1" min="50" max="350" value={Number.isNaN(form.fasting_glucose) ? "" : form.fasting_glucose} onChange={(e) => updateNumber("fasting_glucose", e.target.value)} />{errors.fasting_glucose && <em>{errors.fasting_glucose}</em>}</label>
        <label className="field"><span>eGFR <small>mL/min/1.73m²</small></span><input aria-label="eGFR" type="number" step="0.1" min="15" max="150" value={Number.isNaN(form.egfr) ? "" : form.egfr} onChange={(e) => updateNumber("egfr", e.target.value)} />{errors.egfr && <em>{errors.egfr}</em>}</label>
        <label className="field"><span>Systolic BP <small>mmHg</small></span><input aria-label="Systolic blood pressure" type="number" step="0.1" min="90" max="220" value={Number.isNaN(form.systolic_bp) ? "" : form.systolic_bp} onChange={(e) => updateNumber("systolic_bp", e.target.value)} />{errors.systolic_bp && <em>{errors.systolic_bp}</em>}</label>
        <label className="field"><span>Diastolic BP <small>mmHg</small></span><input aria-label="Diastolic blood pressure" type="number" step="0.1" min="50" max="130" value={Number.isNaN(form.diastolic_bp) ? "" : form.diastolic_bp} onChange={(e) => updateNumber("diastolic_bp", e.target.value)} />{errors.diastolic_bp && <em>{errors.diastolic_bp}</em>}{form.diastolic_bp >= form.systolic_bp && <em>Must be lower than systolic BP.</em>}</label>
      </div>

      <fieldset className="medication-fieldset">
        <legend>Current medications <small>optional</small></legend>
        <div className="medication-list">{medicationOptions.map((medication) => <button type="button" key={medication} className={`medication-chip ${form.current_meds.includes(medication) ? "selected" : ""}`} onClick={() => toggleMedication(medication)} aria-pressed={form.current_meds.includes(medication)}>{medication}<span>{form.current_meds.includes(medication) ? "✓" : "+"}</span></button>)}</div>
      </fieldset>

      <div className="form-footer"><div className="privacy-note"><LockKeyhole size={14} /> Submitted to the configured clinical API only</div><Button className="primary-action" type="submit" disabled={loading || hasErrors}>{loading ? <><Loader2 className="spin" size={16} /> Analyzing patient…</> : <>Analyze patient <ArrowUpRight size={16} /></>}</Button></div>
    </form>
  );
}

function LoadingPanel() {
  return <div className="loading-panel"><div className="loading-orbit"><Activity size={26} /></div><p className="eyebrow teal">Live analysis</p><h2>Reading the clinical signal…</h2><p>Stages below are interface feedback while the connected service processes your request.</p><div className="loading-steps"><div className="active"><CheckCircle2 size={16} /> Validating patient information</div><div className="active"><Loader2 className="spin" size={16} /> Running safety assessment</div><div><span className="step-dot" /> Preparing clinical analysis</div></div></div>;
}

function ResultDashboard({ result, onReset }: { result: ClinicalAnalysisResponse; onReset: () => void }) {
  const emergency = result.status === "emergency" || result.health_report.emergency;
  return <section className="results-view" aria-live="polite">
    <div className={`result-hero ${emergency ? "emergency" : ""}`}>
      <div className="result-hero-top"><div className="hero-status"><span className="signal-dot" /> {emergency ? "Immediate attention" : "Analysis complete"}</div><span className="provenance"><Sparkles size={13} /> Source: backend</span></div>
      <div className="result-hero-grid"><div><p className="eyebrow">Clinical assessment</p><h1>{emergency ? "Urgent professional review required." : "A clear signal for the care team."}</h1><p>{result.health_report.summary}</p></div><div className="score-tile"><span>Risk score</span><strong>{result.risk.score.toFixed(1)}</strong><small>/ 100 · <StatusBadge value={result.risk.level} /></small></div></div>
      {emergency && <div className="emergency-callout"><AlertTriangle size={20} /><div><strong>URGENT MEDICAL ATTENTION REQUIRED</strong><p>{result.health_report.emergency_guidance || "Immediate professional medical evaluation is recommended."}</p></div></div>}
    </div>

    <div className="result-columns"><div className="result-main">
      <div className="result-section"><div className="result-section-title"><div><p className="eyebrow teal">01 / Risk profile</p><h2>What the system observed</h2></div><StatusBadge value={result.risk.level} /></div><div className="metrics-row"><Metric label="Risk level" value={formatLabel(result.risk.level)} /><Metric label="Triage" value={formatLabel(result.triage.category)} /><Metric label="Review" value={result.triage.doctor_review_required ? "Required" : "Not required"} /></div><div className="factor-list">{result.risk.factors.length ? result.risk.factors.map((factor) => <div className="factor-row" key={`${factor.name}-${factor.value}`}><span className="factor-marker" /><div><strong>{factor.name}</strong><p>{factor.explanation}</p></div><span className="factor-value">{factor.value}</span></div>) : <div className="empty-state"><CheckCircle2 size={18} /> No elevated indicators were returned.</div>}</div></div>

      {!emergency && result.treatment_analysis && <div className="result-section"><div className="result-section-title"><div><p className="eyebrow teal">02 / Analytical options</p><h2>Ranked for clinician review</h2></div><span className="provenance">Estimated effect</span></div><p className="section-copy">These are model-generated treatment-effect estimates from the backend, not a prescription or eligibility decision.</p><div className="option-list">{result.treatment_analysis.ranked_options.map((option) => <div className="option-row" key={option.treatment}><div className="rank-number">0{option.rank}</div><div className="option-name"><strong>{option.treatment}</strong><span>Estimated HbA1c effect</span></div><div className="option-effect">{option.estimated_effect > 0 ? "+" : ""}{option.estimated_effect.toFixed(3)}</div><ChevronRight size={16} /></div>)}</div></div>}

      <div className="result-section"><div className="result-section-title"><div><p className="eyebrow teal">03 / Explainability</p><h2>Why the model surfaced this</h2></div><span className="provenance"><Sparkles size={13} /> SHAP</span></div><div className="explanation-grid">{result.health_report.explainability.slice(0, 6).map((item, index) => <div className="explanation-card" key={`${item.feature}-${index}`}><div className="explanation-head"><span>{item.feature}</span><span className={item.contribution >= 0 ? "positive" : "negative"}>{item.contribution >= 0 ? "+" : "−"}{Math.abs(item.contribution).toFixed(3)}</span></div><p>{item.explanation}</p></div>)}</div></div>
    </div><aside className="result-side">
      <div className="side-card navigation-card"><div className="side-icon"><ArrowUpRight size={18} /></div><p className="eyebrow teal">Next step</p><h3>{formatLabel(result.health_report.recommended_next_step)}</h3><p>{result.triage.message}</p><div className="path-line"><span /> Backend care pathway</div></div>
      {result.doctor_case && <div className="side-card doctor-card"><div className="side-card-head"><Stethoscope size={18} /><span>Doctor workflow</span></div><h3>Case ready for review</h3><div className="case-meta"><span>Case ID</span><strong>{result.doctor_case.case_id}</strong><span>Status</span><strong>{formatLabel(result.doctor_case.status)}</strong><span>Priority</span><strong>{formatLabel(result.doctor_case.priority)}</strong></div><p className="muted-note">The connected backend has created this case. Doctor actions are not available in the current API.</p></div>}
      <div className="side-card report-card"><div className="side-card-head"><FileText size={18} /><span>Health report</span></div><h3>{result.health_report.report_id}</h3><p>{result.health_report.disclaimer}</p><div className="report-foot"><Clock3 size={14} /> {result.health_report.case_status === "NOT_CREATED" ? "No doctor case created" : formatLabel(result.health_report.case_status)}</div></div>
    </aside></div>
    <div className="results-footer"><p><LockKeyhole size={14} /> This interface displays AI-assisted analysis. It does not provide a diagnosis or prescription.</p><Button variant="outline" onClick={onReset}><RefreshCw size={15} /> New analysis</Button></div>
  </section>;
}

export default function Home() {
  const [form, setForm] = useState<PatientRequest>(initialForm);
  const [result, setResult] = useState<ClinicalAnalysisResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError("");
    setLoading(true);
    try { setResult(await analyzePatient(form)); } catch (err) {
      if (err instanceof ClinicalApiError) setError(err.message);
      else setError("Unable to connect to the clinical analysis service.");
    } finally { setLoading(false); }
  };

  const reset = () => { setResult(null); setError(""); };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><img src={LOGO_URL} alt="Prism signal mark" /><span className="brand-signal-edge" /></div><div><strong>PRISM</strong><span>Clinical intelligence</span></div></div><nav><a className="nav-link active" href="#analysis"><Activity size={17} /> <span>Patient analysis</span><span className="nav-pulse" /></a><a className="nav-link" href="#workflow" onClick={(e) => e.preventDefault()}><ClipboardCheck size={17} /> <span>Doctor workflow</span><small>API</small></a></nav><div className="sidebar-bottom"><div className="system-status"><span className="online-dot" /> <span>Clinical API connected</span></div><p>Prototype workspace<br />Synthetic data only</p></div></aside><main className="main-canvas" id="analysis"><header className="topbar"><div><p className="eyebrow">Care navigation workspace</p><h1>{result ? "Clinical signal review" : "Patient analysis"}</h1></div><div className="topbar-meta"><span><LockKeyhole size={14} /> Privacy-aware session</span><span className="date-stamp">Live session / 01</span></div></header>{loading ? <LoadingPanel /> : result ? <ResultDashboard result={result} onReset={reset} /> : <div className="intake-layout"><div className="intake-primary"><div className="intro-block"><div className="intro-kicker"><span className="signal-line" /> EARLY SIGNAL DETECTION</div><h2>Make the next<br /><i>clinical move</i> clearer.</h2><p>Connect patient measurements to a transparent, safety-gated care pathway. Start with the data you have.</p></div><PatientForm form={form} setForm={setForm} onSubmit={submit} loading={loading} error={error} /></div><aside className="intake-aside"><div className="aside-illustration"><div className="radar-ring ring-one" /><div className="radar-ring ring-two" /><div className="radar-core"><HeartPulse size={28} /></div><span className="radar-label label-one">SAFETY</span><span className="radar-label label-two">SIGNAL</span><span className="radar-label label-three">REVIEW</span></div><div className="aside-note"><div className="workflow-heading"><span className="workflow-signal" /><p className="eyebrow teal">Workflow telemetry</p></div><div className="mini-step"><span>01</span><div><strong>Input received</strong><p>Patient information enters the validation boundary.</p></div></div><div className="mini-step"><span>02</span><div><strong>Safety boundary</strong><p>Risk, triage, and urgency remain backend-owned.</p></div></div><div className="mini-step"><span>03</span><div><strong>Handoff readiness</strong><p>Cases and reports appear when review is required.</p></div></div></div></aside></div>}<footer className="global-footer">AI-assisted clinical intelligence <span>•</span> Analysis for qualified professional review</footer></main></div>;
}
